import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { API_BASE_URL } from '../../core/api/api.config';

interface Settings { cabinetId: string; reminderDelayMinutes: number; defaultSlotDurationMinutes: number; notificationTexts: Record<string, string>; }
interface Quotas { subscriptionPlan: string; activePractitioners: number; maxPractitioners: number; smsSentThisMonth: number; maxSmsPerMonth: number; }

@Component({ selector: 'app-cabinet-settings', changeDetection: ChangeDetectionStrategy.OnPush, imports: [MatButtonModule, MatCardModule, MatFormFieldModule, MatInputModule, ReactiveFormsModule], template: `
<section class="page" aria-labelledby="settings-title"><p class="eyebrow">ADMINISTRATION / CABINET ACTIF</p><h1 id="settings-title">Paramètres du cabinet</h1><p class="intro">Configurez les rappels et suivez les quotas de votre plan.</p>@if(loading()){<p class="state" role="status">Chargement des paramètres...</p>}@if(error()){<p class="state error" role="alert">Les paramètres sont momentanément indisponibles.</p>}@if(settings();as current){<div class="columns"><mat-card appearance="outlined"><form [formGroup]="form" (ngSubmit)="save()"><h2>Rappels</h2><mat-form-field appearance="outline"><mat-label>Délai de rappel (minutes)</mat-label><input matInput type="number" formControlName="reminderDelayMinutes" /></mat-form-field><mat-form-field appearance="outline"><mat-label>Durée par défaut (minutes)</mat-label><input matInput type="number" formControlName="defaultSlotDurationMinutes" /></mat-form-field><mat-form-field appearance="outline"><mat-label>Texte SMS de rappel</mat-label><textarea matInput formControlName="smsReminder"></textarea></mat-form-field><mat-form-field appearance="outline"><mat-label>Texte email de rappel</mat-label><textarea matInput formControlName="emailReminder"></textarea></mat-form-field>@if(saveError()){<p class="error" role="alert">Enregistrement impossible.</p>}<button mat-flat-button type="submit" [disabled]="form.invalid||saving()">{{saving()?'Enregistrement...':'Enregistrer'}}</button></form></mat-card>@if(quotas();as usage){<mat-card appearance="outlined"><h2>Quotas · {{usage.subscriptionPlan}}</h2><div class="quota"><span>Praticiens actifs</span><strong>{{usage.activePractitioners}} / {{usage.maxPractitioners}}</strong></div><div class="quota"><span>SMS ce mois</span><strong>{{usage.smsSentThisMonth}} / {{usage.maxSmsPerMonth}}</strong></div></mat-card>}</div>}</section>`, styles: `.page{max-width:1100px;margin:auto}.eyebrow{color:#0b7375;font-size:.72rem;font-weight:800;letter-spacing:.16em;margin:0 0 14px}h1{color:#173b3d;font-size:clamp(2.4rem,5vw,4.2rem);line-height:.95;margin:0}.intro{color:#587174;margin:14px 0 32px}.columns{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.7fr);gap:20px}mat-card{padding:24px;border-color:#d9e5e3}form{display:grid;gap:14px}h2{color:#173b3d;font-size:1.15rem}.quota{display:flex;justify-content:space-between;gap:16px;padding:16px 0;border-bottom:1px solid #e5eeee;color:#587174}.quota strong{color:#173b3d}button{background:#0b7375;color:#fff;min-height:44px}.state{padding:32px 0;color:#587174}.error{color:#a33c2f}@media(max-width:760px){.columns{grid-template-columns:1fr}}`, })
export class CabinetSettingsComponent { private readonly http=inject(HttpClient); private readonly baseUrl=inject(API_BASE_URL); private readonly fb=inject(NonNullableFormBuilder); protected readonly settings=signal<Settings|null>(null); protected readonly quotas=signal<Quotas|null>(null); protected readonly loading=signal(true); protected readonly error=signal(false); protected readonly saving=signal(false); protected readonly saveError=signal(false); protected readonly form=this.fb.group({reminderDelayMinutes:[1440,[Validators.min(0),Validators.max(10080)]],defaultSlotDurationMinutes:[30,[Validators.required,Validators.min(5),Validators.max(240)]],smsReminder:[''],emailReminder:['']}); constructor(){this.http.get<Settings>(`${this.baseUrl}/cabinet/settings`).subscribe({next:value=>{this.settings.set(value);this.form.patchValue({reminderDelayMinutes:value.reminderDelayMinutes,defaultSlotDurationMinutes:value.defaultSlotDurationMinutes,smsReminder:value.notificationTexts['smsReminder']??'',emailReminder:value.notificationTexts['emailReminder']??''});this.loading.set(false)},error:()=>{this.error.set(true);this.loading.set(false)}});this.http.get<Quotas>(`${this.baseUrl}/cabinet/quotas`).subscribe({next:value=>this.quotas.set(value),error:()=>undefined})} save():void{if(this.form.invalid)return;const value=this.form.getRawValue();this.saving.set(true);this.saveError.set(false);this.http.patch<Settings>(`${this.baseUrl}/cabinet/settings`,{reminderDelayMinutes:value.reminderDelayMinutes,defaultSlotDurationMinutes:value.defaultSlotDurationMinutes,notificationTexts:{smsReminder:value.smsReminder,emailReminder:value.emailReminder}}).subscribe({next:result=>{this.settings.set(result);this.saving.set(false)},error:()=>{this.saveError.set(true);this.saving.set(false)}})}}
