import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { API_BASE_URL } from '../../core/api/api.config';
import { TenantSessionService } from '../../core/auth/tenant-session.service';
interface Cabinet { id:string; name:string; address?:string; siret?:string; timezone:string; status:string; subscriptionPlan:string; createdAt:string; }
@Component({selector:'app-cabinet-profile',changeDetection:ChangeDetectionStrategy.OnPush,imports:[MatButtonModule,MatCardModule,MatFormFieldModule,MatInputModule,ReactiveFormsModule],template:`<section class="page" aria-labelledby="cabinet-title"><p class="eyebrow">CABINET ACTIF</p><h1 id="cabinet-title">Profil du cabinet</h1>@if(loading()){<p class="state" role="status">Chargement du cabinet...</p>}@if(error()){<p class="state error" role="alert">Le profil du cabinet est momentanément indisponible.</p>}@if(cabinet();as current){<mat-card appearance="outlined"><form [formGroup]="form" (ngSubmit)="save()"><mat-form-field appearance="outline"><mat-label>Nom</mat-label><input matInput formControlName="name" [readonly]="session.role() !== 'ADMIN'" /></mat-form-field><mat-form-field appearance="outline"><mat-label>Adresse</mat-label><input matInput formControlName="address" [readonly]="session.role() !== 'ADMIN'" /></mat-form-field><mat-form-field appearance="outline"><mat-label>SIRET</mat-label><input matInput formControlName="siret" [readonly]="session.role() !== 'ADMIN'" /></mat-form-field><mat-form-field appearance="outline"><mat-label>Fuseau horaire</mat-label><input matInput formControlName="timezone" [readonly]="session.role() !== 'ADMIN'" /></mat-form-field><div class="status"><strong>Statut : {{current.status}}</strong><span>Plan : {{current.subscriptionPlan}}</span></div>@if(session.role()==='ADMIN'){<button mat-flat-button type="submit" [disabled]="form.invalid||saving()">{{saving()?'Enregistrement...':'Enregistrer'}}</button>}</form></mat-card>}</section>`,styles:`.page{max-width:760px;margin:auto}.eyebrow{color:#0b7375;font-size:.72rem;font-weight:800;letter-spacing:.16em;margin:0 0 14px}h1{color:#173b3d;font-size:clamp(2.4rem,5vw,4.2rem);line-height:.95;margin:0 0 32px}mat-card{padding:24px;border-color:#d9e5e3}form{display:grid;gap:14px}.status{display:flex;justify-content:space-between;gap:16px;padding:14px 0;color:#587174}.status strong{color:#173b3d}button{background:#0b7375;color:#fff;min-height:44px}.state{padding:32px 0;color:#587174}.error{color:#a33c2f}@media(max-width:600px){.status{align-items:start;flex-direction:column}}`})
export class CabinetProfileComponent {private readonly http=inject(HttpClient);private readonly baseUrl=inject(API_BASE_URL);private readonly fb=inject(NonNullableFormBuilder);protected readonly session=inject(TenantSessionService);protected readonly cabinet=signal<Cabinet|null>(null);protected readonly loading=signal(true);protected readonly error=signal(false);protected readonly saving=signal(false);protected readonly form=this.fb.group({name:['',[Validators.required]],address:[''],siret:[''],timezone:['',[Validators.required]]});constructor(){this.load()}private load():void{this.http.get<Cabinet>(`${this.baseUrl}/cabinet`).subscribe({next:value=>{this.cabinet.set(value);this.form.patchValue({name:value.name,address:value.address??'',siret:value.siret??'',timezone:value.timezone});this.loading.set(false)},error:()=>{this.error.set(true);this.loading.set(false)}})}save():void{if(this.form.invalid||this.session.role()!=='ADMIN')return;this.saving.set(true);this.http.patch<Cabinet>(`${this.baseUrl}/cabinet`,this.form.getRawValue()).subscribe({next:value=>{this.cabinet.set(value);this.saving.set(false)},error:()=>{this.saving.set(false);this.error.set(true)}})}}
