import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { API_BASE_URL } from '../../core/api/api.config';

@Component({ selector: 'app-appointment-form', changeDetection: ChangeDetectionStrategy.OnPush, imports: [MatButtonModule, MatCardModule, MatFormFieldModule, MatInputModule, MatSelectModule, ReactiveFormsModule, RouterLink], template: `
<section class="page" aria-labelledby="appointment-title"><a routerLink="/planning">← Retour au planning</a><p class="eyebrow">AGENDA / NOUVEAU RENDEZ-VOUS</p><h1 id="appointment-title">Créer un rendez-vous</h1><mat-card appearance="outlined"><form [formGroup]="form" (ngSubmit)="submit()"><mat-form-field appearance="outline"><mat-label>ID patient</mat-label><input matInput formControlName="patientId" /><mat-hint>Identifiant du dossier patient</mat-hint></mat-form-field><mat-form-field appearance="outline"><mat-label>ID appartenance praticien</mat-label><input matInput formControlName="practitionerMembershipId" /></mat-form-field><div class="row"><mat-form-field appearance="outline"><mat-label>Début</mat-label><input matInput type="datetime-local" formControlName="startAt" /></mat-form-field><mat-form-field appearance="outline"><mat-label>Fin</mat-label><input matInput type="datetime-local" formControlName="endAt" /></mat-form-field></div><mat-form-field appearance="outline"><mat-label>Source</mat-label><mat-select formControlName="source"><mat-option value="TELEPHONE">Téléphone</mat-option><mat-option value="SUR_PLACE">Sur place</mat-option><mat-option value="EN_LIGNE">En ligne</mat-option></mat-select></mat-form-field>@if(error()){<p class="error" role="alert">Le rendez-vous n'a pas pu être créé. Vérifiez les identifiants et le créneau.</p>}<button mat-flat-button type="submit" [disabled]="form.invalid || saving()">{{saving()?'Création...':'Créer le rendez-vous'}}</button></form></mat-card></section>`, styles: `.page{max-width:760px;margin:auto}.page>a{color:#0b7375;text-decoration:none}.eyebrow{color:#0b7375;font-size:.72rem;font-weight:800;letter-spacing:.16em;margin:32px 0 14px}h1{color:#173b3d;font-size:clamp(2.4rem,5vw,4.2rem);line-height:.95;margin:0 0 32px}mat-card{padding:24px;border-color:#d9e5e3}form{display:grid;gap:16px}.row{display:grid;grid-template-columns:1fr 1fr;gap:16px}button{background:#0b7375;color:#fff;min-height:44px}.error{color:#a33c2f}@media(max-width:650px){.row{grid-template-columns:1fr}}` })
export class AppointmentFormComponent { private readonly fb=inject(NonNullableFormBuilder); private readonly http=inject(HttpClient); private readonly baseUrl=inject(API_BASE_URL); private readonly router=inject(Router); protected readonly saving=signal(false); protected readonly error=signal(false); protected readonly form=this.fb.group({patientId:['',[Validators.required]],practitionerMembershipId:['',[Validators.required]],careTypeId:[''],startAt:['',[Validators.required]],endAt:['',[Validators.required]],source:['TELEPHONE',[Validators.required]]}); submit():void{if(this.form.invalid)return;this.saving.set(true);this.error.set(false);const value=this.form.getRawValue();this.http.post(`${this.baseUrl}/appointments`,{...value,careTypeId:value.careTypeId||null,startAt:new Date(value.startAt).toISOString(),endAt:new Date(value.endAt).toISOString()}).subscribe({next:()=>void this.router.navigateByUrl('/planning'),error:()=>{this.saving.set(false);this.error.set(true)}});}}
