import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { API_BASE_URL } from '../../core/api/api.config';
interface WaitingEntry { id: string; patientId: string; status: string; }
@Component({ selector: 'app-waiting-list', changeDetection: ChangeDetectionStrategy.OnPush, imports: [MatCardModule, MatIconModule], template: `<section class="page" aria-labelledby="waiting-title"><header><div><p class="eyebrow">PATIENTS EN ATTENTE</p><h1 id="waiting-title">Liste d'attente</h1><p class="intro">Les demandes du cabinet actif.</p></div><button mat-flat-button type="button"><mat-icon aria-hidden="true">person_add</mat-icon>Inscrire un patient</button></header>@if(loading()){<p class="state" role="status">Chargement de la liste...</p>}@if(error()){<p class="state error" role="alert">La liste d'attente est momentanément indisponible.</p>}@if(!loading()&&!error()&&entries().length===0){<mat-card appearance="outlined" class="empty">La liste d'attente est vide.</mat-card>}@for(entry of entries();track entry.id){<mat-card appearance="outlined" class="entry"><mat-icon aria-hidden="true">hourglass_top</mat-icon><div><strong>Patient {{entry.patientId}}</strong><p>Demande {{entry.id}}</p></div><span>{{entry.status}}</span></mat-card>}</section>`, styles: `.page{max-width:1100px;margin:auto}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:32px}.eyebrow{color:#0b7375;font-size:.72rem;font-weight:800;letter-spacing:.16em;margin:0 0 14px}h1{color:#173b3d;font-size:clamp(2.4rem,5vw,4.2rem);line-height:.95;margin:0}.intro{color:#587174}button{background:#0b7375;color:#fff;min-height:44px}.entry{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:16px;padding:18px;margin-bottom:10px;border-color:#d9e5e3}.entry mat-icon{color:#e67e22}.entry p{margin:5px 0 0;color:#71898a}.entry span{color:#0b7375;font-weight:700}.state,.empty{padding:40px;color:#587174}.error{color:#a33c2f}@media(max-width:700px){header{align-items:start;flex-direction:column;gap:18px}}`, })
export class WaitingListComponent { private readonly http=inject(HttpClient); private readonly baseUrl=inject(API_BASE_URL); protected readonly entries=signal<WaitingEntry[]>([]); protected readonly loading=signal(true); protected readonly error=signal(false); constructor(){this.http.get<WaitingEntry[]>(`${this.baseUrl}/waiting-list`).subscribe({next:v=>{this.entries.set(v);this.loading.set(false)},error:()=>{this.error.set(true);this.loading.set(false)}})} }
